---
abstract: 'Edgenexus Manager'
author:
  - 'Edgenexus Limited'
build_requires:
  IO::Tee: '0'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: restrictive
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Edge-Manager
requires:
  AnyEvent::HTTP: '2.25'
  Edge::ClientAPI: '0'
  Edge::Manager::App: '0'
  File::ShareDir: '0'
  FindBin: '0'
  JSON::XS: '0'
  Net::SSLeay: '0'
  common::sense: '0'
  lib: '0'
  perl: '5.022'
version: '1.00'
x_generated_by_perl: v5.30.0
x_serialization_backend: 'YAML::Tiny version 1.73'
