
  
# EdgeNEXUS configuration for echo/echo-ingress

upstreams:
  
  - name: echo-echo-ingress-echoservice-echo-service-80
    servers:
    
      - address: 10.244.0.190
        port: 80
    
  

services:
  
  - hostname: "echoservice"
    resource_type: "ingress"
    resource_name: "echo-ingress"
    resource_namespace: "echo"

    listeners:
    
    
      - port: 80
    

    

    locations:
    
      - path: /
        service_name: "echo-service"
        rewrite: ""
        upstream: "echo-echo-ingress-echoservice-echo-service-80"
        
    

    real_ip_from:
      

    

    

